services:
  - type: web
    name: medical-store-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: MONGO_URI
        fromEnv: MONGO_URI
      - key: GOOGLE_API_KEY
        fromEnv: GOOGLE_API_KEY
